### ISSUE TITLE
GPU is not utilized by default

### ISSUE THREAD

**Issue by ogencoglu** [alirezamshi/RQUGE#2]
Hi,

When I run the example code, I do not see any GPU utilization and it is also relatively slow.

```
rqugescore = load("alirezamsh/rquge")
results = rqugescore.compute(generated_questions=generated_questions, contexts=contexts, answers=answers)
```

Is there some flag to define or check CPU vs GPU in `load` function or `compute` method?

**Comment by alirezamshi** [comment]
Hi,

Sorry for the delay. ```device``` argument should be available in both HF mode and direct setting, as added [here](https://huggingface.co/spaces/alirezamsh/rquge/blob/74947f87bee6659ad8239311b380d3ffe13d8e36/rquge.py#L127) and [here](https://github.com/alirezamshi/RQUGE/blob/250918e81938cb0b1bf30a372e1a91e6baf4a9e2/rquge_score_cli/scorer_cli.py#L69). 

Please let me know if you have further concerns!
